### ISSUE TITLE
Greydragon theme partial incompatibility

### ISSUE THREAD

**Issue by geekitude** [geekitude/piwigo-plugin-simplecopyright#16]
Nothing shows up anywhere

**Comment by geekitude** [comment]
I have been able to add image license but plugin's basic style isn't applied.
CSS needed : 
```css
#tab-meta a.cc img {
  width: 100px;
  margin: 0 10px 0 0;
}
```
